#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint || 
{
    echo '❌ ❌ ❌ Something went wrong with linting.. Not commiting'
}


# Check Prettier standards
npm run check-format ||
(
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Format your files and commit again';
    
    false
)

# Check tsconfig standards
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'